### PR TITLE
Fixes pasting in chinese workshop code in chinese client.

### PR DESCRIPTION
**Pull request by kektram**
Fixes a workshop bug specific to chinese workshop, setting "None" values to "无" instead of "全部禁用", causing projects compiled by overpy to fail to paste to workshop with errors.

### CODE REVIEW

**Comment by Zezombye** [comment]
This will get overridden the next time translations are generated. Either the GUID is wrong, or the translation got updated (in which case this PR would work but we gotta make sure it doesn't get reverted when datatool comes out for the latest update)

**Review by CactusPuppy — CHANGES_REQUESTED** [review]
Some of the changes here are incorrect. Not every "None" value needs to be changed from "无" to "开始加速".

For example, the following code in Simplified Chinese is valid and can be pasted:
```
规则("规则 1")
{
	事件
	{
		持续 - 每名玩家;
		双方;
		全部;
	}

	动作
	{
		开始加速(事件玩家, 矢量(0, 0, 0), 100, 20, 至地图, 无);
	}
}
```
(the above code translated to English)
```
rule("规则 1")
{
	event
	{
		Ongoing - Each Player;
		All;
		All;
	}

	actions
	{
		Start Accelerating(Event Player, Vector(0, 0, 0), 100, 20, To World, None);
	}
}
```

To actually fix the root issue, it would be necessary to find which string GUIDs are incorrect and fixing those, then running the translation task again.

**Comment by CactusPuppy** [comment]
Upon further investigation, it turns out that Overwatch itself isn't giving the right translation when copying, so fixing this translation error would require us to do one of the following:
1. Break decompiling
2. Break compiling (current state)
3. Write code that handles every specific case where Overwatch provides the wrong translation

Given the massive amount of work Option 3 would require, and that Options 1 and 2 are pretty much equally bad, this issue is going to be closed as a "won't fix" for now.

## To obtain an incorrect translation:
1. Import code `XHJYK`
2. Copy the rules to clipboard
3. Paste the rules
4. Note that an error is output in the chat

**Comment by Zezombye** [comment]
Option 3 should be ez to do by manually overriding in astToWorkshop.ts, like I did for a similar bug with Japanese: https://github.com/Zezombye/overpy/blob/e21b5fa2ca2224542b798c04b0c00c0cfb230fc6/src/compiler/astToWorkshop.ts#L468

@kektram please provide the exact overpy code that fails (so we can know exactly which instances of "none" to replace)

**Comment by kektram** [comment]
I didn't do any testing. I only verified it got fixed by manually replacing the invalid none entries with the corrected ones.

I was notified of the issue with these steps:
1) put ur client langauge on CN
2) load code 54cry
3) copy the code from ingame
4) paste it back in

After step 3, I manually replaced all invalid "None" entries with the corrected one, and that allowed me to paste it back in.
I was told this code is compiled with overpy, I believe it to be "Genji parkour"
https://github.com/tylovejoy/genji-framework

**Comment by CactusPuppy** [comment]
If someone wants to fix this bug, all they would have to do is import `XHJYK`, copy the rules, paste, and fix the errors one by one. This will catch all instances where the parser expects the other version of None.

**Pull request closed without merging**
